apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pradyapp-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/pradyumnabits/pradyapp-deploy.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: pradyapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
