apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pradyappbg
  labels:
    app: pradyappbg
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pradyappbg
  template:
    metadata:
      labels:
        app: pradyappbg
    spec:
      containers:
        - name: pradyappbg
          image: argoproj/rollouts-demo:green
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: pradyappbg-service
      previewService: pradyappbg-service-preview
