
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pradyappbg
spec:
  selector:
    matchLabels:
      app: pradyappbg
  replicas: 4
  template:
    metadata:
      labels:
        app: pradyappbg
    spec:
      containers:
      - name: pradyappbg
        image: inventory-ms:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pradyappbg
  labels:
    app: pradyappbg
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pradyappbg
  template:
    metadata:
      labels:
        app: pradyappbg
    spec:
      containers:
        - name: pradyappbg
          image: inventory-ms:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: pradyappbg-service
      previewService: pradyappbg-service-preview

---
apiVersion: v1
kind: Service
metadata:
  name: pradyappbg-service
spec:
  selector:
    app: pradyappbg
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  

---
apiVersion: v1
kind: Service
metadata:
  name: pradyappbg-service-preview
spec:
  selector:
    app: pradyappbg
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
