apiVersion: v1
kind: Service
metadata:
  name: pradyappbg-service
spec:
  selector:
    app: pradyappbg
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  

---
apiVersion: v1
kind: Service
metadata:
  name: pradyappbg-service-preview
spec:
  selector:
    app: pradyappbg
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  
