apiVersion: apps/v1
kind: Deployment
metadata:
  name: prady-app
spec:
  selector:
    matchLabels:
      app: pradyapp2
  replicas: 3
  template:
    metadata:
      labels:
        app: prady-app
    spec:
      containers:
      - name: prady-app
        image: inventory-ms:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
