apiVersion: apps/v1
kind: Deployment
metadata:
  name: pradyapp
spec:
  selector:
    matchLabels:
      app: pradyapp
  replicas: 3
  template:
    metadata:
      labels:
        app: pradyapp
    spec:
      containers:
      - name: pradyapp
        image: nanajanashia/argocd-app:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
